oauth:
  clientid: 
  clientsecret:
  redirecturl: https://phpvulnerabilitydetector.example.com/login/auth/
  scopes:
    - userinfo.email
    - userinfo.profile

redis:
  statestore:
    address: localhost
    port: 6379
    password: 
    database: 1

  cookiestore:
    address: localhost
    port: 6379
    password: 
    database: 0

sql:
  username: phpvulndetect
  password: 
  database: phpvulnerabilitydetector
  address: localhost
  port: 3306

server:
  port: 443
  cert: 
  key: 

log:
  path: ./log
